use std::ops::Range;

use crate::diagnostic::Diagnostic;

#[derive(Clone, Debug)]
pub enum TokenType {
	Ident(String),
	Number(f64),
	String(String),
	Diagnostic(Diagnostic),
	Whitespace,
	Comment,
	QuestionMark,
	At,
	Colon,
	Period,
	Comma,
	Semicolon,
	LeftBracket,
	RightBracket,
	LeftBrace,
	RightBrace,
	LeftParen,
	RightParen,
	LeftChevron,
	LeftChevronEqual,
	RightChevron,
	RightChevronEqual,
	Equal,
	DoubleEqual,
	Arrow,
	Bang,
	BangEqual,
	Percent,
	PercentEqual,
	Plus,
	PlusEqual,
	Minus,
	MinusEqual,
	Star,
	StarEqual,
	Slash,
	SlashEqual,
	And,
	Or,
	Not,
	If,
	In,
	Else,
	While,
	For,
	Component,
	On,
	Extern,
	Import,
	Lods,
	Behavior,
	Template,
	Str,
	Code,
	Num,
	Bool,
	Struct,
	Enum,
	Function,
	Animation,
	Use,
	Return,
	Break,
	Switch,
	Let,
	Alias,
	True,
	False,
	None,
}

#[derive(Clone, Debug)]
pub struct Token(pub TokenType, pub Range<usize>);

impl Token {
	pub fn to_type(&self) -> &'static str {
		use TokenType::*;

		match self.0 {
			Ident(_) => "ident",
			Number(_) => "number",
			String(_) => "string",
			Diagnostic(_) => unreachable!(),
			Whitespace => unreachable!(),
			Comment => unreachable!(),
			QuestionMark => "?",
			At => "at",
			Colon => "colon",
			Period => "period",
			Comma => "comma",
			Semicolon => "semicolon",
			LeftBracket => "[",
			RightBracket => "]",
			LeftBrace => "{",
			RightBrace => "}",
			LeftParen => "(",
			RightParen => ")",
			LeftChevron => "<",
			LeftChevronEqual => "<=",
			RightChevron => ">",
			RightChevronEqual => ">=",
			Equal => "=",
			DoubleEqual => "==",
			Arrow => "=>",
			Bang => "!",
			BangEqual => "!=",
			Percent => "%",
			PercentEqual => "%=",
			Plus => "+",
			PlusEqual => "+=",
			Minus => "-",
			MinusEqual => "-=",
			Star => "*",
			StarEqual => "*=",
			Slash => "/",
			SlashEqual => "/=",
			And => "and",
			Or => "or",
			Not => "not",
			If => "if",
			In => "in",
			Else => "else",
			While => "while",
			For => "for",
			Component => "component",
			On => "on",
			Extern => "extern",
			Import => "import",
			Lods => "lods",
			Behavior => "behavior",
			Template => "template",
			Str => "str",
			Code => "code",
			Num => "num",
			Bool => "bool",
			Struct => "struct",
			Enum => "enum",
			Function => "fn",
			Animation => "animation",
			Use => "use",
			Return => "return",
			Break => "break",
			Switch => "switch",
			Let => "let",
			Alias => "alias",
			True => "true",
			False => "false",
			None => "none",
		}
	}
}
